runtime: python37

env_variables:
  MONGO_URI: ""
  FANFOU_API_KEY: ""
  FANFOU_API_SECRET: ""
  FANFOU_OAUTH_TOKEN: ""
  FANFOU_OAUTH_SECRET: ""
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"

handlers:
  - url: /(.*\.(gif|jpg|jpeg|png|ico))
    static_files: assets/\1
    upload: assets/.*$
  - url: /.*
    script: auto
