runtime: python37

env_variables:
  MONGO_URI: ""
  FANFOU_ACCOUNT: ""
  FANFOU_API_KEY: ""
  FANFOU_API_SECRET: ""
  FANFOU_OAUTH_TOKEN: ""
  FANFOU_OAUTH_SECRET: ""
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
  max_instances: 2
  max_idle_instances: 1

handlers:
  - url: /(.*\.(gif|jpg|jpeg|png|ico))
    static_files: assets/\1
    upload: assets/.*$
  - url: /.*
    script: auto
